import { Inter } from "next/font/google";
import "./globals.css";
import { CurrentEngineProvider } from "./gptContexts/chatEngine";
import { SelectedChatProvider } from "./gptContexts/selectedChat";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CurrentEngineProvider>
      <SelectedChatProvider>
        <html lang="en">
          <body>{children}</body>
        </html>
      </SelectedChatProvider>
    </CurrentEngineProvider>
  );
}
